# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 511)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(20, 20, 851, 431))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.start = QtWidgets.QPushButton(self.groupBox_2)
        self.start.setGeometry(QtCore.QRect(20, 360, 75, 25))
        self.start.setObjectName("start")
        self.filename = QtWidgets.QLineEdit(self.groupBox_2)
        self.filename.setGeometry(QtCore.QRect(20, 30, 191, 20))
        self.filename.setObjectName("filename")
        self.browse = QtWidgets.QPushButton(self.groupBox_2)
        self.browse.setGeometry(QtCore.QRect(220, 30, 75, 23))
        self.browse.setObjectName("browse")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 10, 151, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(20, 390, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 101, 21))
        self.label_2.setObjectName("label_2")
        self.Temperature = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.Temperature.setGeometry(QtCore.QRect(20, 80, 91, 31))
        self.Temperature.setMinimum(-272.0)
        self.Temperature.setMaximum(500.0)
        self.Temperature.setObjectName("Temperature")
        self.Pmin = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.Pmin.setGeometry(QtCore.QRect(20, 140, 91, 31))
        self.Pmin.setMaximum(10.0)
        self.Pmin.setSingleStep(0.1)
        self.Pmin.setObjectName("Pmin")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 191, 21))
        self.label_3.setObjectName("label_3")
        self.Pmax = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.Pmax.setGeometry(QtCore.QRect(20, 200, 91, 31))
        self.Pmax.setMaximum(10.0)
        self.Pmax.setSingleStep(0.1)
        self.Pmax.setObjectName("Pmax")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(20, 180, 201, 21))
        self.label_4.setObjectName("label_4")
        self.Pstep = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.Pstep.setGeometry(QtCore.QRect(20, 260, 91, 31))
        self.Pstep.setMinimum(0.1)
        self.Pstep.setMaximum(1.0)
        self.Pstep.setSingleStep(0.1)
        self.Pstep.setObjectName("Pstep")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 240, 151, 21))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 888, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start.setText(_translate("MainWindow", "Пуск"))
        self.browse.setText(_translate("MainWindow", "Выбрать"))
        self.label.setText(_translate("MainWindow", "Выберите файл"))
        self.pushButton.setText(_translate("MainWindow", "Нарния"))
        self.label_2.setText(_translate("MainWindow", "Температура, *С"))
        self.label_3.setText(_translate("MainWindow", "Давление, нижняя граница (Мпа)"))
        self.label_4.setText(_translate("MainWindow", "Давление, верхняя граница (Мпа)"))
        self.label_5.setText(_translate("MainWindow", "Давление, шаг (Мпа)"))

