# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(883, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(20, 10, 851, 541))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.start = QtWidgets.QPushButton(self.groupBox_2)
        self.start.setGeometry(QtCore.QRect(10, 100, 75, 25))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.start.setFont(font)
        self.start.setStyleSheet("background-color:rgb(170, 0, 0);\n"
"color:white\n"
"")
        self.start.setObjectName("start")
        self.filename = QtWidgets.QLineEdit(self.groupBox_2)
        self.filename.setGeometry(QtCore.QRect(100, 10, 191, 20))
        self.filename.setStyleSheet("background-color:white")
        self.filename.setObjectName("filename")
        self.browse = QtWidgets.QPushButton(self.groupBox_2)
        self.browse.setGeometry(QtCore.QRect(300, 10, 75, 23))
        self.browse.setStyleSheet("background-color:white")
        self.browse.setObjectName("browse")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 101, 21))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.Temperature = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.Temperature.setGeometry(QtCore.QRect(10, 60, 91, 31))
        self.Temperature.setStyleSheet("background-color:white")
        self.Temperature.setMinimum(-272.0)
        self.Temperature.setMaximum(500.0)
        self.Temperature.setObjectName("Temperature")
        self.Pmin = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.Pmin.setGeometry(QtCore.QRect(110, 60, 91, 31))
        self.Pmin.setStyleSheet("background-color:white")
        self.Pmin.setMaximum(10.0)
        self.Pmin.setSingleStep(0.1)
        self.Pmin.setObjectName("Pmin")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(110, 40, 191, 21))
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.Pmax = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.Pmax.setGeometry(QtCore.QRect(290, 60, 91, 31))
        self.Pmax.setStyleSheet("background-color:white")
        self.Pmax.setMaximum(10.0)
        self.Pmax.setSingleStep(0.1)
        self.Pmax.setObjectName("Pmax")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(290, 40, 201, 21))
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.Pstep = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.Pstep.setGeometry(QtCore.QRect(470, 60, 91, 31))
        self.Pstep.setStyleSheet("background-color:white")
        self.Pstep.setMinimum(0.1)
        self.Pstep.setMaximum(1.0)
        self.Pstep.setSingleStep(0.1)
        self.Pstep.setObjectName("Pstep")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(470, 40, 151, 21))
        self.label_5.setStyleSheet("")
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.graph = QtWidgets.QWidget(self.groupBox_2)
        self.graph.setGeometry(QtCore.QRect(19, 139, 811, 381))
        self.graph.setObjectName("graph")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 883, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.start.setText(_translate("MainWindow", "Пуск"))
        self.browse.setText(_translate("MainWindow", "Выбрать"))
        self.label_2.setText(_translate("MainWindow", "Температура, *С"))
        self.label_3.setText(_translate("MainWindow", "Давление, нижняя граница (Мпа)"))
        self.label_4.setText(_translate("MainWindow", "Давление, верхняя граница (Мпа)"))
        self.label_5.setText(_translate("MainWindow", "Давление, шаг (Мпа)"))
        self.label.setText(_translate("MainWindow", "Выберите файл"))

